apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-cluster
  namespace: argo-cd

spec:
  destination:
    namespace: capi-cluster-bw7
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/capi-cluster
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/capi-staging/argocd-apps/capi-cluster.values.yaml
    - repoURL: https://github.com/nihaldivyam/kubeaid-config
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
