apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api
  namespace: argo-cd

spec:
  destination:
    namespace: cluster-api
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/cluster-api
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/capi-staging/argocd-apps/cluster-api.values.yaml
    - repoURL: https://github.com/nihaldivyam/kubeaid-config
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
