apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    path: k8s/capi-staging/kube-prometheus
    repoURL: https://github.com/nihaldivyam/kubeaid-config
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
