apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argo-cd

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    path: k8s/capi-staging/sealed-secrets
    repoURL: https://github.com/nihaldivyam/kubeaid-config
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy: {}
